### ISSUE TITLE
Remove `expect` and `expect-jsx` from devDependencies

### ISSUE THREAD

**Issue by wuct** [MoOx/react-topbar-progress-indicator#1]
Actually, `expect` has not been used in the [test](https://github.com/MoOx/react-topbar-progress-indicator/blob/master/src/__tests__/index.js). Maybe we could remove`expect` and `expect-jsx` from devDependencies?

**Comment by MoOx** [comment]
True :) PR welcome !

**Comment by wuct** [comment]
done :)
