### ISSUE TITLE
Renamed lifecycles in latest React

### ISSUE THREAD

**Issue by adeluca67** [MoOx/react-topbar-progress-indicator#5]
As of React 16.9.0 we're getting warnings while using this handy little progress bar:

`Warning: componentWillMount has been renamed, and is not recommended for use.`
[update-on-async-rendering](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)

We can certainly replace it with our own, but was just wondering if there are plans for a new release which fixes such problems.

**Comment by MoOx** [comment]
Fixed in 3.0.0 :)

**Comment by MoOx** [comment]
4.0.0 is even better as it's vanilla js that use React.useEffect (hope this works in real world, didn't tested my release in production haha)
