### ISSUE TITLE
Breaks in IE11

### ISSUE THREAD

**Issue by tcoughlin3** [MoOx/react-topbar-progress-indicator#8]
IE11 doesn't support arrow functions so it throws a Syntax error when trying to parse the arrow function defaults.

![image](https://user-images.githubusercontent.com/13300310/65899776-0e7b7d00-e37a-11e9-8845-b4c31a7878d8.png)

![image](https://user-images.githubusercontent.com/13300310/65899739-f9065300-e379-11e9-8015-775c8998c271.png)

**Comment by MoOx** [comment]
Oooopsy. Will fix that asap.

**Comment by MoOx** [comment]
Fix shipped in 4.0.2
